wasp-os/wasp-os

README.md

I was looking at wasp-os and needed to get back to instructions for programming bootloader.  I thought handy link towards top of README.md would help me and others.

Link to PineTime page on pine64

---

README.md

As far as I can tell, `set_time` hasn't existed since this commit: https://github.com/daniel-thompson/wasp-os/commit/127df66335657cbd77539a509d507a4fcfb403b2
I haven't been able to track down when it disappeared, but it doesn't exist in the current RTC driver. The original implementation didn't allow for setting the date anyway it seems. This PR updates the readme to reference `set_localtime()` instead.
I couldn't get `set_time()` to work when working through the readme, but I'm new to wasp-os within the last couple of days. Feel free to just close this if I've understood something fundamental.

Fixed the documentation for setting the RTC time

---

wasp/draw565.py

Before, the background color was only applied to the direct background of the characters, as seen in this picture. 
The padding and the spacing between the characters was not affected. After these changes, it now looks as expected when using a custom background color:

Fix background color of strings.

---

tools/wasptool

- Certain Unix-like systems (such as *BSD systems) do not use /usr/bin/python3 as the default Python path. This small change will ensure a higher degree of compatibility.

wasptool: Change Python shebang to ensure compatibility

---

docs/install.rst

The softdevice make target requires unzip

docs: add unzip to environment setup

---

docs/install.rst

Wget needs to be installed to run `make softdevice`. Most distros have it installed by default, but it's better to have it in the list to be sure.

Add wget to build dependencies

---

wasp/draw565.py

Example:
```py
width, height = wasp.watch.drawable.bounding_box("Hello")
```
Warning: This was only tested in the simulator, but it hopefully should not break anything on the watch.
Signed-off-by: kozova1 <mug66kk@gmail.com>

drivers: draw565: Added bounding_box() to check physical size of string

---

wasp/draw565.py

Currently, if the line wrapper attempts to break a line on a space and
that space character is outside the bounding box, then we generate an
over-long line.
Fix this by handling line break generation *after* we have checked the
length of the current line.
Fixes: #193
Signed-off-by: Daniel Thompson <daniel@redfelineninja.org.uk>

draw565: Avoid over-long lines when handling space

---

wasp/apps/settings.py
wasp/apps/weather.py
wasp/boards/simulator/main.py
wasp/wasp.py

When I created the weather app I didn't have GadgetBridge installed, so I tried to follow the protocol on the [espurino website](https://www.espruino.com/Gadgetbridge), but it wasn't very helpful and I made some mistakes. This commit should fix these mistakes to stop the weather app from crashing, and so it displays the correct values. I have also added a new settings option called "Units", where apps can see what units the user would prefer (metric/imperial).
Signed-off-by: Tait Berlette <54515877+taitberlette@users.noreply.github.com>

apps: Fixed weather app with GadgetBridge.

---

.github/workflows/main.yml
Makefile

So that users can just download the .mpy files instead of having to build the whole toolchain

Add make and CI rules for building apps .mpy files

---

wasp/apps/alarm.py

It was too easy to accidentally stop the alarm by touching the screen,
either by moving around or by trying to press the side button to snooze.
Snoozing instead of stopping is better than the opposite because it
poses no risk of missing the alarm, so we swap the controls to:
touch -> snooze
press -> stop
---
I actually missed the alarm a couple of times due to this. I hope it's an uncontroversial change.

Alarm: swap stop and snooze controls

---

wasp/wasp.py

Hi,
It's an issue I had several times in the passed. Right now I'm forking the timerapp and notice that calling wasp.system.switch(self) while the app is not in the background actually resets ticks and stops the watch from vibrating.
I think it's not an expected behavior so I'm proposing this PR.

fix: system.switch(self) when in foreground cancel motor vibrations

---

tools/wasptool

Explicitely tell the user in the help that --binary only applies to --upload. I think this is needed because I thought it could apply to --eval --exec --push and --pull.
Btw: I think it would be good to change the order of the arguments to something more logical instead of alphabetical. If you agree I'll do that after this PR gets merged.

docs: explicit --binary help

---

wasp/wasp.py

I was scratching my head for a while to understand how run was called and found the name misleading.
I think it would also be worth it to be a bit more explicit in explaining how schedule() is called for those like me who are familiar with python but not micropython or electronics.
Signed-off-by: thiswillbeyourgithub <github@32mail.33mail.com>

docs: explain that Manager.run is not usually run

---

wasp/drivers/battery.py

Hi,
Very simple PR to add a comment for newcomers to ignore the PEP8 warning to remove "import Pin" as it stops the battery level from updating as it was one of the first thing I did...

add comment warning to ignore IDE asking to remove unused imports

---

docs/appguide.rst

I'm not sure if this is even good practice. But I learned I could do this by reading the software.py file. I tried to get it to work using the upload command of the wasp tool but couldn't get it to work. But by using the push command I am easily able to store a .mpy so that its automatically added to the software list. 
I personally found this useful but it obviously still has the RAM constraints of a flash based program. I didn't think the docs made it clear this was possible. So I offer this update. If this is encouraging bad practice I'm interested in that as well.
Signed-off-by: Adam Blair adampblair@protonmail.com

Doc update: how to autoload apps in flash

---

Makefile

Not every distro calls it `pytest-3`.
By using `$(PYTHON) -m` we ensure it's coherent with the python install
Closes #417

Use `python -m` to run pytest

---

docs/install.rst
tools/nix/flake.nix
tools/nix/shell.nix

Another way to get the toolchain on any linux and osx system. I've been using this since I started using wasp-os, and it's been working fine

Add nix development shell

---

wasp/wasp.py

There currently appears to be no way to remove a tick request, and calling this func without args gives:
self.tick_expiry = watch.rtc.get_uptime_ms() + period_ms
~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

wasp: Allow for clearing a tick request

---

wasp/boards/k9/watch.py.in
wasp/boards/p8/watch.py.in
wasp/boards/pinetime/watch.py.in

Fixes #307 : rebooting the watch while the HRS light is on will not turn it off.
Signed-off-by: thiswillbeyourgithub <github@32mail.33mail.com>

new: disable ppg light by default on startup

---

wasp/draw565.py

This avoids running unnecessary code and avoids a bug in set_window().
For background see #251

Small change to fill() to exit early if there is nothing to do.

---

docs/install.rst

Most new users of WASP-OS do not know the limitations and may attempt to autoload a number of applications that exceed the watch RAM capacity. So the user will have to reduce the number of applications chosen and re-install. This doc change has updates from DanielT (#465) and fgaz (#468) that I was not able to merge in those pr's.

docs: installation: --update normal operations

---

docs/install.rst

Updated wasp-bootloader and wasp-os installation for Android using Gadgetbridge. Ready for review.

docs: installation: Installing wasp-bootloader and wasp-os --Gadgetbridge

---

docs/appguide.rst

Corrected the path for the main.py file for running the simulator.

docs:awg:run:simulator -- fix main.py path

---

tools/nix/shell.nix

Fixes "ImportError: cannot import name GLib, introspection typelib not found"

tools/nix: fix wasptool

---

docs/install.rst

This way we can ditch the pip footgun by default

docs: update system requirements to newer distros
