wasp-os/wasp-os

wasp/boards/pinetime/watch.py
=> wasp: pinetime: Release SPI NOR from deep power-down

.github/workflows/main.yml, Makefile
This is Panagiotis Vasilopoulos's PR rebased and converted into a PR so that I can experiment with the workflow.
=> Added GitHub Actions support

.github/workflows/main.yml, docs/appguide.rst
Signed-off-by: Daniel Thompson <daniel@redfelineninja.org.uk>
=> github: actions: Ensure warning free docs build

.github/workflows/sim.yml, Makefile, docs/install.rst, wasp/boards/simulator/test_smoke.py, wasp/requirements.txt
Signed-off-by: Daniel Thompson <daniel@redfelineninja.org.uk>
=> simulator: Add some basic fully automatic tests

tools/test_theme.py, tools/themer.py, wasp/apps/calc.py, wasp/apps/chrono.py, wasp/apps/clock.py, wasp/apps/heart.py, wasp/apps/steps.py, wasp/apps/stopwatch.py, wasp/wasp.py, wasp/widgets.py
This commit adds the option to change the color of the bars in the
heartrate app.
Signed-off-by: kozova1 <mug66kk@gmail.com>
=> Added Heartrate app theming.

wasp/apps/software.py
It especially helps loading big user defined apps.
=> Collect garbage before enabling apps

tools/wasptool
=> fix: wasptool --pull fails when downloading nested file

wasp/widgets.py
I think this is pretty useful for some timer apps like my sleep tracker.
=> new: add increment size argument in Spinner widgets

apps/Morse.py
I also took the liberty of switching to lowercase.
There is no ability to move the cursor, I somehow lost that WIP a while ago.
=> feat: morse app saves text to file + erase + space + newline

wasp/apps/flashlight.py
Touch the flashlight app to cycle through brightness levels as well as colors (I find red light more agreable when I'm lost at night but often need the white light too).
Signed-off-by: thiswillbeyourgithub <github@32mail.33mail.com>
=> new: brightness and color change of flashlight

wasp/apps/alarm.py
- docs: mention that pressing the button will stop the watch
- feat: save alarms across reboots
- new: increment minutes by 5 instead of 1
edit : so far only tested on the simulator because my watch has a weird non related issue that makes troubleshooting a bit difficult at the moment.
=> feat: save alarms across reboots

wasp/drivers/battery.py
Signed-off-by: thiswillbeyourgithub <github@32mail.33mail.comm>
edit : I reworked the code to smoothen the voltage instead of the level
=> fix: smoothen battery level before showing it to user

wasp/drivers/battery.py
I noticed the issue of battery level not being reset (#385) and fixed it on my own fork recently. I'm low on time currently but figured I would at least PR my current version.
I'm sorry for all this :/
=> fix: battery level is not reset when charging without rebooting

Makefile
https://stackoverflow.com/questions/52437728/bash-what-is-the-difference-between-pwd-and-curdir
=> Makefile: use CURDIR instead of PWD

wasp/wasp.py
I think this is useful. I'm behind an alarm app with snooze and lots of other features so keeping track of every time an action is scheduled can be cumbersome.
Signed-off-by: thiswillbeyourgithub <github@32mail.33mail.com>
=> feat: remove any alarm given an action

wasp/gadgetbridge.py
Simplified `send_cmd` in `gadgetbridge.py`
=> Simplify send_cmd in gadgetbridge.py

wasp/boards/simulator/watch.py
Signed-off-by: thiswillbeyourgithub <26625900+thiswillbeyourgithub@users.noreply.github.com>
=> fix: simulator was missing some time functions

tools/wasptool
Signed-off-by: olivier-cornelis <klduycea@mailer.me>
=> new: allow to specify local name of file when using wasptool pull with argument 'as'

docs/contributing.rst
It's a little less destructive
=> docs: contributing: use --force-with-lease instead of --force

.readthedocs.yaml, docs/requirements.txt
Looks like recommonmark is needed https://readthedocs.org/projects/wasp-os/builds/22389134/
Also fixes #477
=> Fix docs issues

tools/wasptool
I fixed the issues with my previous commit (#426), please review again Francesco.
Thank you!
=> added send notification feature

tools/nix/shell.nix
Alternative to #494, but even if we go for #494 we should probably merge this too since nobody thoroughly tested newer versions yet
=> Pin GCC 11 in nix shell

.github/workflows/main.yml
https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/
=> CI: update upload-artifact

Makefile
Mitigates #506. Now a `make clean && make` will update any modified app.
=> Add some missing files to make clean

.github/workflows/main.yml, .github/workflows/sim.yml
Shouldn't hurt. I checked the changelogs.
=> ci: update more github actions
